### ISSUE TITLE
Unity 2019.1.6f1

### ISSUE THREAD

**Issue by Nrjwolf** [smkplus/CustomToolbar#1]
I have errors after fix using that UIElements no longer in Experimental

<img width="966" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/10683971/68771839-d2566000-0639-11ea-89a8-1fa41af2c74a.png">

**Comment by baba-s** [comment]
I fixed the error by changing the program below in local.

- Unity 2019.2.9f1

### ToolbarCallback.cs

#### Before

```cs
using System;
using UnityEngine;
using UnityEditor;
using System.Reflection;
using UnityEngine.Experimental.UIElements;
```

#### After

```cs
using System;
using UnityEngine;
using UnityEditor;
using System.Reflection;

#if UNITY_2019_1_OR_NEWER
using UnityEngine.UIElements;
#else
using UnityEngine.Experimental.UIElements;
#endif
```

### ToolbarExtender.cs

#### Before

```cs
static ToolbarExtender()
{
	Type toolbarType = typeof(Editor).Assembly.GetType("UnityEditor.Toolbar");
	FieldInfo toolIcons = toolbarType.GetField("s_ShownToolIcons",
		BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
	m_toolCount = toolIcons != null ? ((Array) toolIcons.GetValue(null)).Length : 6;

	ToolbarCallback.OnToolbarGUI -= OnGUI;
	ToolbarCallback.OnToolbarGUI += OnGUI;
}
```

#### After

```cs
static ToolbarExtender()
{
	Type toolbarType = typeof(Editor).Assembly.GetType("UnityEditor.Toolbar");
	FieldInfo toolIcons = toolbarType.GetField("s_ShownToolIcons",
		BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
	var array = ( Array ) toolIcons.GetValue( null );
	m_toolCount = array != null ? array.Length : 6;

	ToolbarCallback.OnToolbarGUI -= OnGUI;
	ToolbarCallback.OnToolbarGUI += OnGUI;
}
```

**Comment by smkplus** [comment]
> I fixed the error by changing the program below in local.
> 
> * Unity 2019.2.9f1
> 
> ### ToolbarCallback.cs
> #### Before
> ```cs
> using System;
> using UnityEngine;
> using UnityEditor;
> using System.Reflection;
> using UnityEngine.Experimental.UIElements;
> ```
> 
> #### After
> ```cs
> using System;
> using UnityEngine;
> using UnityEditor;
> using System.Reflection;
> 
> #if UNITY_2019_1_OR_NEWER
> using UnityEngine.UIElements;
> #else
> using UnityEngine.Experimental.UIElements;
> #endif
> ```
> 
> ### ToolbarExtender.cs
> #### Before
> ```cs
> static ToolbarExtender()
> {
> 	Type toolbarType = typeof(Editor).Assembly.GetType("UnityEditor.Toolbar");
> 	FieldInfo toolIcons = toolbarType.GetField("s_ShownToolIcons",
> 		BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
> 	m_toolCount = toolIcons != null ? ((Array) toolIcons.GetValue(null)).Length : 6;
> 
> 	ToolbarCallback.OnToolbarGUI -= OnGUI;
> 	ToolbarCallback.OnToolbarGUI += OnGUI;
> }
> ```
> 
> #### After
> ```cs
> static ToolbarExtender()
> {
> 	Type toolbarType = typeof(Editor).Assembly.GetType("UnityEditor.Toolbar");
> 	FieldInfo toolIcons = toolbarType.GetField("s_ShownToolIcons",
> 		BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
> 	var array = ( Array ) toolIcons.GetValue( null );
> 	m_toolCount = array != null ? array.Length : 6;
> 
> 	ToolbarCallback.OnToolbarGUI -= OnGUI;
> 	ToolbarCallback.OnToolbarGUI += OnGUI;
> }
> ```

thanks @baba-s 
can you pull request it?

**Comment by baba-s** [comment]
> can you pull request it?

@smkplus

https://github.com/smkplus/CustomToolbar/pull/2

:smile:
