### ISSUE TITLE
Opening scene in read-only package!

### ISSUE THREAD

**Issue by smkplus** [smkplus/CustomToolbar#11]
it's not allowed to open a scene in read-only package
![image](https://user-images.githubusercontent.com/16706911/100459960-99b9e500-30db-11eb-9666-a2bb8d0b319b.png)

**Comment by inertiave** [comment]
Unity Editor doesn't allow to open scene in read-only package. When you include any playable scene to custom package, you should add samples manifest in package.json.

```json
{
  "name": "com.unity.my.custom.package",
  "displayName": "My Custom Package",
  "version": "1.0.0",
  "description": "My Custom Package",
  "samples": [
  	{
  		"displayName": "Demo Scenes",
  		"description": "playable samples scenes",
  		"path": "Samples~/Demo Scene"
  	}]
}
```
with following directory structure.
```
com.unity.my.custom.package
- Editor
- Runtime
- Samples~
-- Demo Scene
```

then, the menu button that import samples will be visualized on package manager panel.

see the [fixed branch](https://github.com/smkplus/CustomToolbar/pull/13)
