### ISSUE TITLE
 It's impossible to set the framerate upper than 120 FPS

### ISSUE THREAD

**Issue by smkplus** [smkplus/CustomToolbar#14]
@Team-on 
120 is the maximum FPS I can set in the tool, but my screen can run 144Hz, so I would like to set 144FPS.
There are also screen with 250Hz (more expensive), and those screens are limited by half of their max frequency

I think that, by default, you must limit the max FPS by retrieving the Resolution.refreshRate of the Monitor.

https://docs.unity3d.com/ScriptReference/Resolution-refreshRate.html

**Comment by inertiave** [comment]
You can edit max frame in [script](https://github.com/smkplus/CustomToolbar/blob/master/Editor/CustomToolbar/Scripts/CustomToolbarRight.cs#L34).
change 120 to the number you want.

I'll PR that export this value to option.

**Comment by Team-on** [comment]
Hey guys.
Can you explain how to work with new project hierarchy? I didn't know how to launch it in Unity and test changes when there are no root assets folder

**Comment by inertiave** [comment]
Do you mean how to create new project? Then launch unity hub and create a new project to hit the blue button named `NEW`. If you have trouble with this custom package repository, you should create a new project and import package by package manager.

**Comment by Team-on** [comment]
Well, I know how to import packages.
I doesn't know how to set up this repository for contributing. Usually I just pull code from git -> open unity project -> make changes -> commit&merge. But this repository is not recognized as unity project

**Comment by smkplus** [comment]
@Team-on sorry I had to remove Assets Folder and stuff because of the package.json problem. actually, this is the first time that I use the package.json and I watched the tutorial that they put the package.json in the root folder.
I'm not sure why using package.json in Asset folder doesn't work.
maybe @cqtd can help us to fix this issue.

**Comment by inertiave** [comment]
My Development directory

![image](https://user-images.githubusercontent.com/51351749/100615833-8452ee00-335b-11eb-9b29-463810651ec7.png)

![image](https://user-images.githubusercontent.com/51351749/100615844-8ae16580-335b-11eb-8a1e-4600bfe75454.png)

![image](https://user-images.githubusercontent.com/51351749/100615856-8e74ec80-335b-11eb-97c5-a6ff2fb1dd8f.png)


1. Create a project through Unity Hub.
2. clone repository at `Package` folder at root of project.
3. edit codes with your IDE.

**Comment by Team-on** [comment]
@cqtd Thank you, that exactly what I looking for. 
So probably we should create some *contribution guidelines* how to set up a repository, if it's not so obvious?

**Comment by nnra6864** [comment]
Whilst it's easy to configure this, I would recommend setting the default lowest value to -1.
As far as I know, that should uncap the game fps.
