### ISSUE TITLE
Publish at Asset store?

### ISSUE THREAD

**Issue by Team-on** [smkplus/CustomToolbar#25]
What about publishing asset at Unity Asset Store? I think that asset pretty usefull and it should be in the store.

**Comment by smkplus** [comment]
@Team-on 
Hi, dear friend
that's a Good Idea!
actually these days I'm busy.
It would great if you publish this asset.
feel free to publish this asset!

**Comment by Team-on** [comment]
Ok, I'll publish that

**Comment by Team-on** [comment]
Here it are 
https://assetstore.unity.com/packages/tools/utilities/custom-toolbar-189047
