### ISSUE TITLE
Cannot distinguish scenes with the same name.

### ISSUE THREAD

**Issue by inertiave** [smkplus/CustomToolbar#8]
In some cases, most of asset from asset store provides several example scenes that uses common names such as `Main.unity`, `SampleScene.unity`, `Scene.unity` and `Test.unity`. Distinguishing by name of scene might cause malfunction. So my suggestion is to use path to take uniqueness instead of name. 

If you don't mind, I'll PR [this branch](https://github.com/cqtd/CustomToolbar/commit/c2639f2c75bb717aca814adea0f270c7e7475c9b).
Appreciate.

**Comment by Team-on** [comment]
I'm not a maintainer, but I am the one who commit that feature. 

It definitely useful when project contains many assets, so why not. 

I have plans to make some settings in Project Settings for this asset, so I think it would be usefull to toggle between scene full path and name.

**Comment by smkplus** [comment]
@Team-on 
@cqtd 
Thank you guys for contributing!😊
I'm really happy that you like my repo and it's useful😎👌

**Comment by inertiave** [comment]
Thanks. I sent PR.

**Comment by smkplus** [comment]
@Team-on
@cqtd
Thank you guys for contributing!😊
I'm really happy that you like my repo and it's useful😎👌

I fixed this problem by separating scenes with the same name with folders

![image](https://user-images.githubusercontent.com/16706911/99971855-0323b600-2db3-11eb-9841-5d8533cb9a8c.png)

**Comment by inertiave** [comment]
Cool!

**Comment by inertiave** [comment]
I checked again this, but I still have same issue because most of asset stores the scene in '.../scenes' directory.

My scenes are placed such as `Assets/Scenes/Main.unity`, `Asset/Scenes/Bootstrap.unity`.
And most assets placed sample scenes at `Assets/${{ Plugin Name }}/Example/Scenes/SampleScene.unity`

**Comment by smkplus** [comment]
@cqtd 
Hmmm so If you fixed this problem I'll merge your pull request

**Comment by smkplus** [comment]
@cqtd
your changes make some problems
I can't open scenes that aren't in the build settings
![image](https://user-images.githubusercontent.com/16706911/100459242-632f9a80-30da-11eb-95d8-ed7dc3d8cb24.png)

**Comment by inertiave** [comment]
Thanks. :D
